name: dqn_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - aom=3.9.1
  - asttokens=3.0.0
  - attr=2.5.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.10.16
  - cuda-cudart=12.6.77
  - cuda-cudart_linux-64=12.6.77
  - cuda-nvrtc=12.6.85
  - cuda-nvtx=12.6.77
  - cuda-version=12.6
  - cudnn=9.3.0.75
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.1.1
  - double-conversion=3.3.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - farama-notifications=0.0.4
  - ffmpeg=7.1.0
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freeglut=3.2.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2024.12.0
  - gdk-pixbuf=2.42.12
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - gymnasium=1.0.0
  - harfbuzz=9.0.0
  - hdf5=1.14.4
  - icu=75.1
  - imath=3.1.12
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jasper=4.2.4
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.6
  - libclang13=19.1.6
  - libcublas=12.6.4.1
  - libcufft=11.3.0.4
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.77
  - libcurl=8.11.1
  - libcusolver=11.7.1.2
  - libcusparse=12.5.4.2
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.22.5
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgpg-error=1.51
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm19=19.1.6
  - liblzma=5.6.3
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.6.85
  - libopenblas=0.3.28
  - libopencv=4.10.0
  - libopengl=1.7.0
  - libopenvino=2024.5.0
  - libopenvino-auto-batch-plugin=2024.5.0
  - libopenvino-auto-plugin=2024.5.0
  - libopenvino-hetero-plugin=2024.5.0
  - libopenvino-intel-cpu-plugin=2024.5.0
  - libopenvino-intel-gpu-plugin=2024.5.0
  - libopenvino-intel-npu-plugin=2024.5.0
  - libopenvino-ir-frontend=2024.5.0
  - libopenvino-onnx-frontend=2024.5.0
  - libopenvino-paddle-frontend=2024.5.0
  - libopenvino-pytorch-frontend=2024.5.0
  - libopenvino-tensorflow-frontend=2024.5.0
  - libopenvino-tensorflow-lite-frontend=2024.5.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.2
  - libprotobuf=5.28.2
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libudev1=256.9
  - libuuid=2.38.1
  - libuv=1.49.2
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.6
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nccl=2.23.4.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - opencv=4.10.0
  - openexr=3.3.2
  - openh264=2.5.0
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.54.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - py-opencv=4.10.0
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pyside6=6.7.3
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytz=2024.1
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt6-main=6.7.3
  - rdma-core=55.0
  - readline=8.2
  - setuptools=75.6.0
  - six=1.17.0
  - sleef=3.7
  - snappy=1.2.1
  - stable-baselines3=2.4.0
  - stack_data=0.6.3
  - svt-av1=2.3.0
  - swig=4.3.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstd=1.5.6
  - pip:
      - ale-py==0.10.1
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - certifi==2024.12.14
      - charset-normalizer==3.4.0
      - click==8.1.7
      - idna==3.10
      - imageio==2.36.1
      - imageio-ffmpeg==0.5.1
      - moviepy==2.1.1
      - pillow==10.4.0
      - proglog==0.1.10
      - python-dotenv==1.0.1
      - requests==2.32.3
      - urllib3==2.2.3
